Repository cityofaustin/janis, pull requests merged in 2019-10, with the labels that each got.

#563 3010 circleci
  .circleci/config.yml
  .circleci/docker/deploy.sh
  .circleci/docker/janis-ci-deploy.Dockerfile
  .circleci/scripts/branchConfig.js
  .circleci/scripts/buildNetlifySite.js
  .circleci/scripts/print_vars.sh
  deploy/docker-entrypoint.sh
  deploy/nginx.conf
  netlify.toml
  netlify/publish-netlify-pr.sh
  package.json
  scripts/build-joplin-cloud.sh
  src/components/_Controllers/CMSPreview.js
  src/js/helpers/fetchData.js
Labels: wip

#559 3152 riffin
  package.json
  scripts/build-local-ie.sh
  src/App.js
  src/components/PageSections/ContextualNav/RelatedToMobile.js
  src/components/PageSections/ContextualNav/index.js
  src/components/PageSections/Footer/index.js
  src/components/PageSections/TopicCollectionCards/index.js
  src/components/Pages/Departments.js
  src/components/Pages/Guide/GuideSectionCollection.js
  src/components/Pages/Guide/index.js
  src/components/Pages/Information.js
  src/components/Pages/OfficialDocumentList.js
  src/components/Pages/Service.js
  src/components/Pages/Topic.js
  src/components/Pages/TopicCollection.js
  src/components/_Controllers/CMSPreview.js
  src/js/helpers/cleanData.js
  src/js/queries/all311Query.js
  src/js/queries/allDepartmentPagesQuery.js
  src/js/queries/allDepartmentsQuery.js
  src/js/queries/allGuidePagesQuery.js
  src/js/queries/allInformationPagesQuery.js
  src/js/queries/allOfficialDocumentPagesQuery.js
  src/js/queries/allServicePagesQuery.js
  src/js/queries/allTopicCollectionsQuery.js
  src/js/queries/allTopicsQuery.js
  src/js/queries/departmentPageFragment.js
  src/js/queries/getContextualNavDepartmentDataQuery.js
  src/js/queries/getContextualNavTopicDataQuery.js
  src/js/queries/getDepartmentPageQuery.js
  src/js/queries/getDepartmentsPageQuery.js
  src/js/queries/getGuidePageQuery.js
  src/js/queries/getInformationPageQuery.js
  src/js/queries/getOfficialDocumentPageQuery.js
  src/js/queries/getServicePageQuery.js
  src/js/queries/getTopicCollectionPageQuery.js
  src/js/queries/getTopicPageQuery.js
  src/js/queries/guidePageFragment.js
  src/js/queries/informationPageFragment.js
  src/js/queries/servicePageFragment.js
  src/js/queries/siteStructureQuery.js
  static.config.js
Labels: PR: reviewed-approved

#584 Master -> Prod
  package.json
  scripts/build-local-ie.sh
  src/App.js
  src/components/PageSections/ContextualNav/RelatedToMobile.js
  src/components/PageSections/ContextualNav/index.js
  src/components/PageSections/Footer/index.js
  src/components/PageSections/TopicCollectionCards/index.js
  src/components/Pages/Departments.js
  src/components/Pages/Guide/GuideSectionCollection.js
  src/components/Pages/Guide/index.js
  src/components/Pages/Information.js
  src/components/Pages/OfficialDocumentList.js
  src/components/Pages/Service.js
  src/components/Pages/Topic.js
  src/components/Pages/TopicCollection.js
  src/components/_Controllers/CMSPreview.js
  src/js/helpers/cleanData.js
  src/js/queries/all311Query.js
  src/js/queries/allDepartmentPagesQuery.js
  src/js/queries/allDepartmentsQuery.js
  src/js/queries/allGuidePagesQuery.js
  src/js/queries/allInformationPagesQuery.js
  src/js/queries/allOfficialDocumentPagesQuery.js
  src/js/queries/allServicePagesQuery.js
  src/js/queries/allTopicCollectionsQuery.js
  src/js/queries/allTopicsQuery.js
  src/js/queries/departmentPageFragment.js
  src/js/queries/getContextualNavDepartmentDataQuery.js
  src/js/queries/getContextualNavTopicDataQuery.js
  src/js/queries/getDepartmentPageQuery.js
  src/js/queries/getDepartmentsPageQuery.js
  src/js/queries/getGuidePageQuery.js
  src/js/queries/getInformationPageQuery.js
  src/js/queries/getOfficialDocumentPageQuery.js
  src/js/queries/getServicePageQuery.js
  src/js/queries/getTopicCollectionPageQuery.js
  src/js/queries/getTopicPageQuery.js
  src/js/queries/guidePageFragment.js
  src/js/queries/informationPageFragment.js
  src/js/queries/servicePageFragment.js
  src/js/queries/siteStructureQuery.js
  static.config.js
Labels: PR: unreviewed

#587 fix info page preview
  src/js/helpers/cleanData.js
Labels: PR: unreviewed

#588 fix info page preview -> prod
  src/js/helpers/cleanData.js
Labels: PR: unreviewed

#585 1650 react static 7
  .circleci/scripts/branchConfig.js
  package.json
  src/App.js
  src/components/I18n/I18nController.js
  src/components/I18n/I18nLink.js
  src/components/PageSections/ContextualNav/RelatedToMobile.js
  src/components/PageSections/ContextualNav/index.js
  src/components/PageSections/Footer/index.js
  src/components/PageSections/LanguageSelectBar/index.js
  src/components/PageSections/Menu/MenuInfo.js
  src/components/PageSections/TopicCollectionCards/index.js
  src/components/Pages/Department.js
  src/components/Pages/Departments.js
  src/components/Pages/Guide/index.js
  src/components/Pages/Home.js
  src/components/Pages/Information.js
  src/components/Pages/OfficialDocumentList.js
  src/components/Pages/Service.js
  src/components/Pages/Services.js
  src/components/Pages/Theme.js
  src/components/Pages/Themes.js
  src/components/Pages/Topic.js
  src/components/Pages/TopicCollection.js
  src/components/Tiles/Tile.js
  src/components/Tiles/TileGroup.js
  src/components/WorkInProgress/index.js
  src/components/_Controllers/CMSLive.js
  src/components/_Controllers/CMSPreview.js
  static.config.js
  yarn.lock
Labels: PR: unreviewed

#589 fix it
  static.config.js
Labels: PR: unreviewed

#580 Issue 3202: implement Form Page
  .circleci/scripts/branchConfig.js
  .gitignore
  package.json
  sandbox/App.js
  sandbox/README.md
  sandbox/app.scss
  sandbox/index.html
  sandbox/webpack.config.js
  src/App.js
  src/components/Pages/Form.js
  src/components/Pages/_Form.scss
  src/components/_Controllers/CMSPreview.js
  src/css/coa.scss
  src/js/helpers/cleanData.js
  src/js/queries/formPageFragment.js
  src/js/queries/getFormPageQuery.js
  src/js/queries/getFormPageRevisionQuery.js
  src/js/queries/getTopicPageQuery.js
  src/js/queries/globalGuidePagesQuery.js
  src/js/queries/globalInformationPagesQuery.js
  src/js/queries/globalOfficialDocumentPagesQuery.js
  src/js/queries/globalServicePagesQuery.js
  static.config.js
  yarn.lock
Labels: PR: unreviewed

#590 Master > Prod Form Container
  .circleci/scripts/branchConfig.js
  .gitignore
  package.json
  sandbox/App.js
  sandbox/README.md
  sandbox/app.scss
  sandbox/index.html
  sandbox/webpack.config.js
  src/App.js
  src/components/I18n/I18nController.js
  src/components/I18n/I18nLink.js
  src/components/PageSections/ContextualNav/RelatedToMobile.js
  src/components/PageSections/ContextualNav/index.js
  src/components/PageSections/Footer/index.js
  src/components/PageSections/LanguageSelectBar/index.js
  src/components/PageSections/Menu/MenuInfo.js
  src/components/PageSections/TopicCollectionCards/index.js
  src/components/Pages/Department.js
  src/components/Pages/Departments.js
  src/components/Pages/Form.js
  src/components/Pages/Guide/index.js
  src/components/Pages/Home.js
  src/components/Pages/Information.js
  src/components/Pages/OfficialDocumentList.js
  src/components/Pages/Service.js
  src/components/Pages/Services.js
  src/components/Pages/Theme.js
  src/components/Pages/Themes.js
  src/components/Pages/Topic.js
  src/components/Pages/TopicCollection.js
  src/components/Pages/_Form.scss
  src/components/Tiles/Tile.js
  src/components/Tiles/TileGroup.js
  src/components/WorkInProgress/index.js
  src/components/_Controllers/CMSLive.js
  src/components/_Controllers/CMSPreview.js
  src/css/coa.scss
  src/js/helpers/cleanData.js
  src/js/queries/formPageFragment.js
  src/js/queries/getFormPageQuery.js
  src/js/queries/getFormPageRevisionQuery.js
  src/js/queries/getTopicPageQuery.js
  src/js/queries/globalGuidePagesQuery.js
  src/js/queries/globalInformationPagesQuery.js
  src/js/queries/globalOfficialDocumentPagesQuery.js
  src/js/queries/globalServicePagesQuery.js
  static.config.js
  yarn.lock
Labels: PR: unreviewed

#591 Revert "Master > Prod Form Container"
  .circleci/scripts/branchConfig.js
  .gitignore
  package.json
  sandbox/App.js
  sandbox/README.md
  sandbox/app.scss
  sandbox/index.html
  sandbox/webpack.config.js
  src/App.js
  src/components/I18n/I18nController.js
  src/components/I18n/I18nLink.js
  src/components/PageSections/ContextualNav/RelatedToMobile.js
  src/components/PageSections/ContextualNav/index.js
  src/components/PageSections/Footer/index.js
  src/components/PageSections/LanguageSelectBar/index.js
  src/components/PageSections/Menu/MenuInfo.js
  src/components/PageSections/TopicCollectionCards/index.js
  src/components/Pages/Department.js
  src/components/Pages/Departments.js
  src/components/Pages/Form.js
  src/components/Pages/Guide/index.js
  src/components/Pages/Home.js
  src/components/Pages/Information.js
  src/components/Pages/OfficialDocumentList.js
  src/components/Pages/Service.js
  src/components/Pages/Services.js
  src/components/Pages/Theme.js
  src/components/Pages/Themes.js
  src/components/Pages/Topic.js
  src/components/Pages/TopicCollection.js
  src/components/Pages/_Form.scss
  src/components/Tiles/Tile.js
  src/components/Tiles/TileGroup.js
  src/components/WorkInProgress/index.js
  src/components/_Controllers/CMSLive.js
  src/components/_Controllers/CMSPreview.js
  src/css/coa.scss
  src/js/helpers/cleanData.js
  src/js/queries/formPageFragment.js
  src/js/queries/getFormPageQuery.js
  src/js/queries/getFormPageRevisionQuery.js
  src/js/queries/getTopicPageQuery.js
  src/js/queries/globalGuidePagesQuery.js
  src/js/queries/globalInformationPagesQuery.js
  src/js/queries/globalOfficialDocumentPagesQuery.js
  src/js/queries/globalServicePagesQuery.js
  static.config.js
  yarn.lock
Labels: PR: unreviewed

#592 Revert "Revert "Master > Prod Form Container""
  .circleci/scripts/branchConfig.js
  .gitignore
  package.json
  sandbox/App.js
  sandbox/README.md
  sandbox/app.scss
  sandbox/index.html
  sandbox/webpack.config.js
  src/App.js
  src/components/I18n/I18nController.js
  src/components/I18n/I18nLink.js
  src/components/PageSections/ContextualNav/RelatedToMobile.js
  src/components/PageSections/ContextualNav/index.js
  src/components/PageSections/Footer/index.js
  src/components/PageSections/LanguageSelectBar/index.js
  src/components/PageSections/Menu/MenuInfo.js
  src/components/PageSections/TopicCollectionCards/index.js
  src/components/Pages/Department.js
  src/components/Pages/Departments.js
  src/components/Pages/Form.js
  src/components/Pages/Guide/index.js
  src/components/Pages/Home.js
  src/components/Pages/Information.js
  src/components/Pages/OfficialDocumentList.js
  src/components/Pages/Service.js
  src/components/Pages/Services.js
  src/components/Pages/Theme.js
  src/components/Pages/Themes.js
  src/components/Pages/Topic.js
  src/components/Pages/TopicCollection.js
  src/components/Pages/_Form.scss
  src/components/Tiles/Tile.js
  src/components/Tiles/TileGroup.js
  src/components/WorkInProgress/index.js
  src/components/_Controllers/CMSLive.js
  src/components/_Controllers/CMSPreview.js
  src/css/coa.scss
  src/js/helpers/cleanData.js
  src/js/queries/formPageFragment.js
  src/js/queries/getFormPageQuery.js
  src/js/queries/getFormPageRevisionQuery.js
  src/js/queries/getTopicPageQuery.js
  src/js/queries/globalGuidePagesQuery.js
  src/js/queries/globalInformationPagesQuery.js
  src/js/queries/globalOfficialDocumentPagesQuery.js
  src/js/queries/globalServicePagesQuery.js
  static.config.js
  yarn.lock
Labels: PR: unreviewed

#579 3187 - Translate dates in official document content types
  .circleci/scripts/branchConfig.js
  src/components/Pages/OfficialDocument.js
Labels: PR: unreviewed
