Repository cityofaustin/janis, pull requests merged in 2020-08, with the labels that each got.

#784 no react-router-dom links
  .circleci/scripts/branchConfig.js
  src/components/I18n/I18nLink.js
  src/components/PageSections/ContextualNav/RelatedToMobile.js
  src/components/PageSections/ContextualNav/index.js
  src/components/PageSections/EventsHomePage/index.js
  src/components/PageSections/Footer/index.js
  src/components/PageSections/LanguageSelectBar/index.js
  src/components/PageSections/Menu/MenuInfo.js
  src/components/PageSections/PendingTranslation/index.js
  src/components/PageSections/RelatedEvents/index.js
  src/components/PageSections/TopicCollectionCards/index.js
  src/components/Pages/EventList/EventListEntry.js
  src/components/Pages/OfficialDocuments/OfficialDocumentEntry.js
  src/components/Tiles/Tile.js
  src/components/Tiles/TileGroup.js
  src/components/WorkInProgress/index.js
Labels: PR: reviewed-approved

#836 v3.6.0 master => production
  .circleci/scripts/branchConfig.js
  package.json
  src/components/Contact/_Contact.scss
  src/components/Pages/Location/LocationInfo.js
  src/components/Pages/Location/LocationServiceList.js
  src/components/Pages/Location/_Location.scss
  src/components/Pages/OfficialDocuments/OfficialDocumentCollection.js
Labels: PR: unreviewed

#839 Janis to 3.6.1
  .circleci/scripts/branchConfig.js
  src/js/helpers/searchWorker.js
Labels: PR: unreviewed

#783 4404 News list page
  .circleci/scripts/branchConfig.js
  package.json
  src/components/I18n/I18nLink.js
  src/components/PageSections/ContextualNav/RelatedToMobile.js
  src/components/PageSections/ContextualNav/index.js
  src/components/PageSections/EventsHomePage/index.js
  src/components/PageSections/Footer/index.js
  src/components/PageSections/LanguageSelectBar/index.js
  src/components/PageSections/Menu/MenuInfo.js
  src/components/PageSections/Pagination/_Pagination.scss
  src/components/PageSections/Pagination/paginationContainer.js
  src/components/PageSections/PendingTranslation/index.js
  src/components/PageSections/RelatedEvents/index.js
  src/components/PageSections/TopicCollectionCards/index.js
  src/components/Pages/Department.js
  src/components/Pages/EventList/EventListEntry.js
  src/components/Pages/News/NewsList.js
  src/components/Pages/News/_News.scss
  src/components/Pages/News/index.js
  src/components/Pages/OfficialDocuments/OfficialDocumentEntry.js
  src/components/Pages/_Department.scss
  src/components/Pages/_Page.scss
  src/components/Tiles/Tile.js
  src/components/Tiles/TileGroup.js
  src/components/WorkInProgress/index.js
  src/js/i18n/definitions.js
  src/js/i18n/locales/en.json
  src/js/i18n/locales/es.json
  src/js/queries/departmentPageFragment.js
  src/js/queries/getNewsListPageQuery.js
  static.config.js
Labels: PR: partially-approved

#841 Janis to 3.7.0
  .circleci/scripts/branchConfig.js
  package.json
  src/components/ExternalLink/_ExternalLink.scss
  src/components/ExternalLink/index.js
  src/components/I18n/I18nLink.js
  src/components/PageSections/ContextualNav/RelatedToMobile.js
  src/components/PageSections/ContextualNav/_ContextualNav.scss
  src/components/PageSections/ContextualNav/index.js
  src/components/PageSections/EventsHomePage/index.js
  src/components/PageSections/Footer/index.js
  src/components/PageSections/Header/_Header.scss
  src/components/PageSections/Header/index.js
  src/components/PageSections/LanguageSelectBar/index.js
  src/components/PageSections/Menu/FullSiteMenu.js
  src/components/PageSections/Menu/MenuInfo.js
  src/components/PageSections/Menu/ThemesNav.js
  src/components/PageSections/Menu/ThemesTopicsMenu.js
  src/components/PageSections/Menu/_FullSiteMenu.scss
  src/components/PageSections/Menu/_ThemesTopicMenuMobile.scss
  src/components/PageSections/Pagination/_Pagination.scss
  src/components/PageSections/Pagination/paginationContainer.js
  src/components/PageSections/PendingTranslation/index.js
  src/components/PageSections/RelatedEvents/index.js
  src/components/PageSections/SearchBar/_SearchIcon.scss
  src/components/PageSections/TopicCollectionCards/index.js
  src/components/Pages/Department.js
  src/components/Pages/EventList/EventListEntry.js
  src/components/Pages/News/NewsList.js
  src/components/Pages/News/_News.scss
  src/components/Pages/News/index.js
  src/components/Pages/OfficialDocuments/OfficialDocumentEntry.js
  src/components/Pages/Search/_Search.scss
  src/components/Pages/_Department.scss
  src/components/Pages/_Page.scss
  src/components/Tiles/Tile.js
  src/components/Tiles/TileGroup.js
  src/components/UserFeedback/_UserFeedback.scss
  src/components/WorkInProgress/WorkInProgressBanner.js
  src/components/WorkInProgress/index.js
  src/css/base/_variables.scss
  src/css/coa.scss
  src/js/i18n/definitions.js
  src/js/i18n/locales/en.json
  src/js/i18n/locales/es.json
  src/js/queries/departmentPageFragment.js
  src/js/queries/getNewsListPageQuery.js
  static.config.js
Labels: PR: unreviewed

#848 staging -> prod v3.7.1
  .circleci/scripts/branchConfig.js
  src/components/PageSections/SearchBar/_SearchBar.scss
  src/components/PageSections/SearchBar/index.js
  src/components/Pages/Search/_SearchResult.scss
  src/components/Pages/Search/index.js
  src/components/Pages/Search/searchResult.js
  src/js/helpers/searchIndexBuilder.js
Labels: PR: unreviewed
