Repository cityofaustin/janis, pull requests merged in 2020-03, with the labels that each got.

#697 3818 events view on the homepage
  .circleci/scripts/branchConfig.js
  package.json
  src/components/PageHeader/_PageHeader.scss
  src/components/PageSections/EventsHomePage/_EventsHomePage.scss
  src/components/PageSections/EventsHomePage/index.js
  src/components/Pages/EventList/EventListEntry.js
  src/components/Pages/Home.js
  src/components/Pages/_EventList.scss
  src/css/coa.scss
  src/js/i18n/definitions.js
  src/js/i18n/locales/es.json
  src/js/queries/getEventPageQuery.js
  static.config.js
Labels: PR: reviewed-approved

#714 change relatedDepartments to departments
  src/js/queries/guidePageFragment.js
  src/stories/pages/GuidePage/GuidePage.data.js
Labels: PR: reviewed-approved

#715 master --> prod 2.7.2
  .circleci/scripts/branchConfig.js
  package.json
  src/components/PageHeader/_PageHeader.scss
  src/components/PageSections/EventsHomePage/_EventsHomePage.scss
  src/components/PageSections/EventsHomePage/index.js
  src/components/Pages/EventList/EventListEntry.js
  src/components/Pages/Home.js
  src/components/Pages/_EventList.scss
  src/css/coa.scss
  src/js/i18n/definitions.js
  src/js/i18n/locales/es.json
  src/js/queries/getEventPageQuery.js
  src/js/queries/guidePageFragment.js
  src/stories/pages/GuidePage/GuidePage.data.js
  static.config.js
Labels: PR: unreviewed

#716 4096 remove related department refs
  src/components/Pages/Form.js
  src/components/Pages/Guide/index.js
  src/components/Pages/Information.js
  src/components/Pages/OfficialDocuments/OfficialDocumentList.js
  src/components/_Controllers/CMSPreview.js
  src/js/helpers/cleanData.js
  src/js/queries/topServicesQuery.js
  static.config.js
Labels: PR: reviewed-approved

#718 2.73 -- related departments cleanup
  src/components/Pages/Form.js
  src/components/Pages/Guide/index.js
  src/components/Pages/Information.js
  src/components/Pages/OfficialDocuments/OfficialDocumentList.js
  src/components/_Controllers/CMSPreview.js
  src/js/helpers/cleanData.js
  src/js/queries/topServicesQuery.js
  static.config.js
Labels: PR: unreviewed

#717 4053 scroll to top
  src/App.js
Labels: PR: unreviewed

#719 4059 - addresses include a link to open map
  src/components/Contact/Address.js
  src/components/Pages/Department.js
  src/components/Pages/Event/EventDetailCard/EventLocationDetail.js
  src/components/Pages/Location/LocationInfo.js
  src/js/i18n/definitions.js
  src/js/i18n/locales/es.json
Labels: PR: unreviewed

#725 4154 covid alert
  src/App.js
  src/components/HomepageAlert/_HomepageAlert.scss
  src/components/HomepageAlert/index.js
  src/css/coa.scss
  src/js/i18n/definitions.js
  src/js/i18n/locales/es.json
Labels: PR: unreviewed

#726 2.8.1 include covid 19 banner
  src/App.js
  src/components/HomepageAlert/_HomepageAlert.scss
  src/components/HomepageAlert/index.js
  src/css/coa.scss
  src/js/i18n/definitions.js
  src/js/i18n/locales/es.json
Labels: PR: unreviewed

#713 3690 incremental
  .circleci/config.yml
  .circleci/scripts/branchConfig.js
  .circleci/scripts/buildPublisherV2.js
  static.config.js
Labels: PR: unreviewed, wip

#724 4158 Implement COVID-19 hours alert on location pages
  src/App.js
  src/components/Alerts/_Alerts.scss
  src/components/Alerts/index.js
  src/components/Alerts/locationsCOVID_19.js
  src/components/Pages/Location/LocationInfo.js
  src/css/coa.scss
  src/js/i18n/locales/es.json
Labels: PR: reviewed-approved

#728 Master -> prod v2.8.2
  src/App.js
  src/components/Alerts/_Alerts.scss
  src/components/Alerts/index.js
  src/components/Alerts/locationsCOVID_19.js
  src/components/Pages/Location/LocationInfo.js
  src/css/coa.scss
  src/js/i18n/locales/es.json
Labels: PR: unreviewed

#727 3899 broken build with top level service pages
  .circleci/scripts/branchConfig.js
  src/components/Pages/Service.js
  src/js/queries/servicePageFragment.js
Labels: PR: unreviewed

#729 2.8.3 - checking if service page is global
  .circleci/scripts/branchConfig.js
  src/components/Pages/Service.js
  src/js/queries/servicePageFragment.js
Labels: PR: unreviewed

#696 3967 - Styling/localization for privacy fallback message
  src/components/ErrorMessages/RowContainer.js
  src/components/ErrorMessages/_RowContainer.scss
  src/components/Pages/Form.js
  src/components/SVGs/InfoI.js
  src/js/i18n/definitions.js
  src/js/i18n/locales/en.json
  src/js/i18n/locales/es.json
Labels: PR: unreviewed, wip

#730 master -> prod v2.8.4
  src/components/ErrorMessages/RowContainer.js
  src/components/ErrorMessages/_RowContainer.scss
  src/components/Pages/Form.js
  src/components/SVGs/InfoI.js
  src/js/i18n/definitions.js
  src/js/i18n/locales/en.json
  src/js/i18n/locales/es.json
Labels: PR: unreviewed
