Repository cityofaustin/janis, pull requests merged in 2020-05, with the labels that each got.

#741 Build everything
  src/components/Pages/Home.js
  src/components/Pages/Information.js
  src/js/helpers/cleanData.js
Labels: PR: unreviewed, wip

#757 v 3.0.1 master => production
  .circleci/scripts/buildPublisherV2.js
Labels: PR: unreviewed

#759 v3.0.2 master => production
  .circleci/scripts/buildPublisherV2.js
Labels: PR: unreviewed

#765 3.0.4
  .circleci/scripts/branchConfig.js
  pull_request_template.md
  src/js/helpers/cleanData.js
  static.config.js
Labels: PR: unreviewed

#767 master -> prod 3.0.5
  .circleci/scripts/branchConfig.js
  package.json
  src/components/Pages/Search.js
  src/components/Pages/Search/index.js
  src/components/Pages/Search/searchResult.js
  src/js/helpers/searchIndexBuilder.js
  src/js/queries/allPagesQuery.js
  static.config.js
Labels: PR: unreviewed

#769 janis to 3.1.0, related events on pages
  .circleci/scripts/branchConfig.js
  src/components/PageSections/EventsHomePage/index.js
  src/components/PageSections/RelatedEvents/_RelatedEvents.scss
  src/components/PageSections/RelatedEvents/index.js
  src/components/Pages/EventList/EventListEntry.js
  src/components/Pages/Information.js
  src/components/Pages/Location/LocationRelatedEvents.js
  src/components/Pages/Location/_Location.scss
  src/components/Pages/Location/index.js
  src/components/Pages/Service.js
  src/components/Pages/_EventList.scss
  src/css/coa.scss
  src/js/helpers/cleanData.js
  src/js/queries/allPagesQuery.js
  src/js/queries/informationPageFragment.js
  src/js/queries/locationPageFragment.js
  src/js/queries/servicePageFragment.js
  static.config.js
Labels: PR: unreviewed

#772 Master -> Prod v3.1.1
  static.config.js
Labels: PR: unreviewed

#775 Master -> Prod v3.1.2
  src/components/PageHeader/_PageHeader.scss
Labels: PR: unreviewed

#776 Master -> Prod 3.1.3
  scripts/build-full-local.sh
  src/components/Pages/Location/_Location.scss
  src/components/Pages/Location/index.js
  src/components/UserFeedback/_UserFeedback.scss
Labels: PR: unreviewed

#777 master -> prod v3.2.0
  package.json
  src/components/Contact/_Contact.scss
  src/components/PageHeader/index.js
  src/components/Pages/News/_News.scss
  src/components/Pages/News/index.js
  src/components/Pages/_Page.scss
  src/components/_Controllers/CMSPreview.js
  src/css/coa.scss
  src/js/i18n/definitions.js
  src/js/i18n/locales/en.json
  src/js/queries/allPagesQuery.js
  src/js/queries/getPageRevisionQuery.js
  src/js/queries/newsPageFragment.js
  static.config.js
Labels: PR: unreviewed

#779 drop it from 20 to 10
  .circleci/scripts/branchConfig.js
  src/js/queries/allPagesQuery.js
Labels: wip

#780 master -> prod v3.2.1
  .circleci/scripts/branchConfig.js
  src/js/queries/allPagesQuery.js
Labels: PR: unreviewed

#782 master -> prod v3.2.2
  .circleci/scripts/branchConfig.js
  src/components/PageHeader/_PageHeader.scss
  src/components/Pages/EventList/EventListEntry.js
  src/components/Pages/Form.js
  src/components/Pages/OfficialDocuments/_OfficialDocument.scss
  src/components/Pages/Search/_Search.scss
  src/components/Pages/Search/_SearchResult.scss
  src/components/Pages/Search/index.js
  src/components/Pages/Search/searchResult.js
  src/components/Pages/_404.scss
  src/css/animations/_loader.scss
  src/css/base/_mixins.scss
  src/css/base/_variables.scss
  src/css/coa.scss
  src/js/animations/loader.js
  src/js/helpers/searchIndexBuilder.js
  src/js/helpers/searchWorker.js
  src/js/i18n/definitions.js
  src/js/i18n/locales/es.json
  src/js/queries/allPagesQuery.js
Labels: PR: unreviewed
