Repository cityofaustin/janis, pull requests merged in 2020-09, with the labels that each got.

#849 prod to 3.8.0
  .circleci/scripts/branchConfig.js
  package.json
  src/components/Pages/OfficialDocuments/OfficialDocumentEntry.js
  src/components/Pages/OfficialDocuments/OfficialDocumentPage.js
Labels: PR: unreviewed

#853 Issue 4776: make searchIndex for Elasticsearch
  .circleci/scripts/branchConfig.js
  .gitignore
  docker-compose-elasticsearch.yml
  package.json
  src/components/Pages/Search/searchResult.js
  src/js/helpers/cleanData.js
  src/js/helpers/searchIndexBuilder.js
  src/js/queries/allPagesQuery.js
  src/js/queries/locationPageFragment.js
  static.config.js
  template.env
  yarn.lock
Labels: PR: unreviewed

#856 v3.9.0 master => prod
  .circleci/scripts/branchConfig.js
  .gitignore
  docker-compose-elasticsearch.yml
  package.json
  src/components/Pages/Search/searchResult.js
  src/js/helpers/cleanData.js
  src/js/helpers/searchIndexBuilder.js
  src/js/queries/allPagesQuery.js
  src/js/queries/locationPageFragment.js
  static.config.js
  template.env
  yarn.lock
Labels: PR: unreviewed

#855 4893 Update homepage banner image
  .circleci/scripts/branchConfig.js
  static.config.js
Labels: PR: partially-approved

#858 staging -> prod v3.9.1
  .circleci/scripts/branchConfig.js
  static.config.js
Labels: PR: unreviewed

#852 4830 Global nav: remaining styling
  .circleci/scripts/branchConfig.js
  src/components/PageBanner/_PageBanner.scss
  src/components/PageSections/Header/index.js
  src/components/PageSections/Menu/FullSiteMenu.js
  src/components/PageSections/Menu/_FullSiteMenu.scss
  src/css/base/_variables.scss
Labels: PR: unreviewed

#861 decrease batchSize
  static.config.js
Labels: PR: unreviewed

#862 set batchsize for production and non-production
  static.config.js
Labels: PR: reviewed-approved

#863 staging -> prod v3.9.2
  .circleci/scripts/branchConfig.js
  LICENSE.txt
  src/components/PageBanner/_PageBanner.scss
  src/components/PageSections/Header/index.js
  src/components/PageSections/Menu/FullSiteMenu.js
  src/components/PageSections/Menu/_FullSiteMenu.scss
  src/css/base/_variables.scss
  static.config.js
Labels: PR: unreviewed
